### ISSUE TITLE
Building on x64 Arch WSL

### ISSUE THREAD

**Issue by erhan-** [icedream/denon-prime4#10]
Hey great repository you two and great progress so far. Funny that Doom is coming later than X and Wayland :)

I am trying to build for my Prime GO but only tried yet via my Arch WSL. The compile-buildroot.sh gets stuck currently at the following point:

```
....exec /bin/sh .././configure "--srcdir=.." "--enable-builddir=x86_64-pc-linux-gnu" "linux
gnu"
configure: WARNING: unrecognized options: --disable-gtk-doc, --disable-gtk-doc-html, --disable-doc, --disable-documentation, --with-xmlto, --with-fop, --disable-nls
.././configure: line 2304: config.log: No such file or directory
.././configure: line 2314: config.log: No such file or directory
cat: standard output: No such file or directory
make: *** [package/pkg-generic.mk:241: /mnt/c/Users/Erhan/Documents/Arch/denon-primego-icedream-experiments/buildroot/2021.02.10/output/build/host-libffi-3.3/.stamp_configured] Error 1
make: Leaving directory '/mnt/c/Users/Erhan/Documents/Arch/denon-primego-icedream-experiments/buildroot/2021.02.10'
```

I think I have to get my Linux VM running instead or my Linux on my other partition. There are also problem with the mount command.

```
 sudo ./mount.sh                                             chroot: failed to run command ‘sh’: Exec format error 
```

Do I have to compile and be on an arm system as well to be able to chroot and also later run the systemctl commands after build?

My filter knob broke off so I want to remap the microphone button and knobs for that :) Also I saw some bluetooth binaries. I would like to check if maybe a connection to a BT speaker is possible.

Danke für alles. Geile Sache :D

**Comment by icedream** [comment]
@erhan- Ah, there's something I forgot to document!

The issue would be that you don't have qemu binfmt-registered to run ARM binaries for you. I have installed the packages `qemu-user-static` and from AUR `binfmt-qemu-static` (which just installs a file `/usr/lib/binfmt.d/qemu-static.conf`) to set that up with my own Arch WSL2 instance, so you can try that or something similar to that.

WSL1 won't work for this I think, if you use that.

Gern geschehen! :)

**Comment by erhan-** [comment]
I still got the error so I switched to my Archlinux system which was a bit dusty. Upgraded everything and started the process there as well. First, you have to run the unpack.sh script twice. Second, the error is the same at the end of the build process. I guess where it adds the openssh stuff:

`chroot: failed to run command ‘sh’: Exec format error`

**Comment by icedream** [comment]
Weird that unpack.sh had to be run twice. Would be interesting to see the whole log for that.

And yes that would again be binfmt not being correctly set up. As described above the script expects QEMU to take over the access to the operating system for ARM binaries, so you would make sure to run the binfmt filesystem (on Arch that should be `systemctl start systemd-binfmt`) and QEMU should have registered through that with above mentioned packages installed.

I don't know what else to suggest at the moment.

**Comment by erhan-** [comment]
Thanks for the hint. I started my Arch up again and checked via systemctl. It showed as active but I tried the start command anyway. Compiling and packing worked. I dont know if it was the restart.

Unfortunately, the PrimeGo reboots to update mode but then just starts the old system normally as if it is not accepting the .img. I have to test further.

**Comment by erhan-** [comment]
Hey, I tried again clean but no luck. Have you also put the img file on a stick to update or are you using the Windows flash tool? That one does not exist for the Prime Go unfortunately, I think.
