### ISSUE TITLE
PRIME4-2.3.2-ssh-Update.img is not ssh patched

### ISSUE THREAD

**Issue by dzelionis** [icedream/denon-prime4#31]
Hey,

Comparing PRIME4-2.3.2-ssh-Update.img root fs and  PRIME4-2.3.2-ssh-Update.exe root fs, looks like the one not in self extracting firmware was never patched to enable ssh.....

**Comment by dzelionis** [comment]
i have just now tried to flash extracted rootfs from PRIME4-2.3.2-ssh-Update.exe and ssh just worked out of box...but it's not working if you use PRIME4-2.3.2-ssh-Update.img

**Comment by icedream** [comment]
I'll look into what happened with the .img file. I probably mixed up versions of the build there.

**Comment by icedream** [comment]
Updated the .img with the one shipped as part of the .exe for now.

**Comment by dzelionis** [comment]
no worries i have already running 2.4.0 with root access....

**Comment by icedream** [comment]
Managed to get a 2.4.0 release out now as well that hopefully works as intended, so this issue is now definitely obsolete. 😄
