### ISSUE TITLE
Release for Prime GO

### ISSUE THREAD

**Issue by erhan-** [icedream/denon-prime4#40]
Hey icedream,

if you have time, could you also make a release for the Prime GO please? I was never successful with this and would just like to see if it is my setup or an issue in general.

Thanks for this project!

Best regards
Erhan

**Comment by icedream** [comment]
There is ongoing work for supporting the other devices but none of them are testable at all for me. I might get an image going in the next few days and then link it here for testing if you're okay with that?

**Comment by erhan-** [comment]
Yes, absolutely.

**Comment by icedream** [comment]
@erhan- Here's a test build. Let me know if it fails or succeeds to update and boot!

If you need the .img you should be able to extract it from the .exe with 7z.

https://github.com/icedream/denon-prime4/releases/download/v3.0.0-ssh%2Bprimego.alpha.1/PRIMEGO-3.0.0-ssh+primego.alpha.1-Update.exe

**Comment by erhan-** [comment]
Geil, it works!

**Comment by icedream** [comment]
I've started adding Prime GO firmware regularly to releases, so I'll close this. Thanks for your feedback!

**Comment by erhan-** [comment]
Thank you very much. It is still a super good device. Especially with all the updates it receives.
